project:
  type: website
  output-dir: docs

website:
  title: "Home_Page"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    right:
      - text: Profile
        href: index.qmd
      
format:
  html:
    # theme: [cosmo, styles.scss]
    # theme: united
    # theme: Sandstone
    theme: 
     - cosmo
     - styles.scss
    fontsize: 1.2em
    linestretch: 1.2
    backgroundcolor: rgb(250, 250, 250)

execute:
  freeze: auto
  
  